services:
  simple-frontend:
    build: .
    container_name: llamaseek-frontend
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - WATCHPACK_POLLING=true
    restart: always
    networks:
      - llamaseek-network
  
  # Uncomment and configure the backend service as needed
  # backend:
  #   image: llamaseek-backend:latest  # Replace with your backend image
  #   container_name: llamaseek-backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend-data:/app/data
  #   environment:
  #     - DEBUG=true
  #     - HOST=0.0.0.0
  #     - PORT=8000
  #     - CORS_ORIGINS=["http://localhost:3002"]
  #   restart: always
  #   networks:
  #     - llamaseek-network

networks:
  llamaseek-network:
    driver: bridge 