version: '3.8'

services:
  simple-frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3002:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
